/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package item.weapon;

import item.Item;

/**
 *
 * @author Luiz
 */
public class ItemSword extends Item {

    public ItemSword(String name) {
        super.itemCanAge = true;
        switch (name) {
            case "0-Cutter":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Cutter";
                super.itemImgDir = "/assets/item/weapon/sword/0a.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.MINintegrity = 15;
                super.MAXintegrity = 25;
                super.MINatkMin = 1;
                super.MAXatkMin = 2;
                super.MINatkMax = 3;
                super.MAXatkMax = 3;
                super.atkSpd = 7;
                super.MINatkRtg = 50;
                super.MAXatkRtg = 56;
                super.critChance = 1;
                super.classSpec = new String[]{KS, MS, FS, ASS, ATS, SS}; 
                super.sAtkSpd = 1;
                super.sMINmagicAPT = 100;
                super.sMAXmagicAPT = 100;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 3;
                super.Display = 1;
                super.weight = 2;
                super.price = 60;
                super.itemLore = "";

                break;

            case "0-Celtic Blade":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Celtic Blade";
                super.itemImgDir = "/assets/item/weapon/sword/0b.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.MINintegrity = 18;
                super.MAXintegrity = 31;
                super.MINatkMin = 2;
                super.MAXatkMin = 2;
                super.MINatkMax = 4;
                super.MAXatkMax = 5;
                super.atkSpd = 7;
                super.MINatkRtg = 55;
                super.MAXatkRtg = 62;
                super.critChance = 1;
                super.classSpec = new String[]{KS, ATS}; 
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 3;
                super.Display = 1;
                super.weight = 3;
                super.price = 250;
                super.itemLore = "";

                break;

            case "0-Sword Beaker":
                    
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Sword Breaker";
                super.itemImgDir = "/assets/item/weapon/sword/0c.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rStr = 30;
                super.MINintegrity = 30;
                super.MAXintegrity = 35;
                super.MINatkMin = 2;
                super.MAXatkMin = 3;
                super.MINatkMax = 6;
                super.MAXatkMax = 7;
                super.atkSpd = 7;
                super.MINatkRtg = 45;
                super.MAXatkRtg = 52;
                super.critChance = 2;
                super.classSpec = new String[]{KS, MS, FS, ATS}; 
                super.sAtkSpd = 1;
                super.sDivAtkPow = 4;
                super.Display = 1;
                super.weight = 4;
                super.price = 560;
                super.itemLore = "";

                break;

            case "0-Samurai Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Samurai Sword";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Duration = 604800;
                super.itemLore = "";

                break;

            case "0-Halloween Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Halloween Sword";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Duration = 120;
                super.itemLore = "";

                break;

            case "0-Halloween Knife":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Halloween Knife";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Duration = 120;
                super.itemLore = "";

                break;

            case "0-Love Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Love Sword";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.MINhpReg = 20;
                super.MAXhpReg = 20;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sHpReg = 5;
                super.Display = 1;
                super.weight = 5;
                super.price = 1000;
                super.itemLore = "";

                break;

            case "0-Xmas Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Xmas Sword";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Duration = 120;
                super.itemLore = "";

                break;

            case "0-Xmas Knife":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Xmas Knife";
                super.itemImgDir = "/assets/item/weapon/sword/0.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Duration = 120;
                super.itemLore = "";

                break;

            case "6-Short Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Short Sword";
                super.itemImgDir = "/assets/item/weapon/sword/6.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 6;
                super.rStr = 36;
                super.MINintegrity = 40;
                super.MAXintegrity = 48;
                super.MINatkMin = 3;
                super.MAXatkMin = 4;
                super.MINatkMax = 5;
                super.MAXatkMax = 8;
                super.atkSpd = 8;
                super.MINatkRtg = 38;
                super.MAXatkRtg = 44;
                super.critChance = 3;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 4;
                super.Display = 1;
                super.weight = 5;
                super.price = 1300;
                super.itemLore = "";

                break;

            case "9-Long Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Long Sword";
                super.itemImgDir = "/assets/item/weapon/sword/9.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 9;
                super.rStr = 40;
                super.rTal = 30;
                super.MINintegrity = 48;
                super.MAXintegrity = 55;
                super.MINatkMin = 7;
                super.MAXatkMin = 8;
                super.MINatkMax = 11;
                super.MAXatkMax = 13;
                super.atkSpd = 7;
                super.MINatkRtg = 40;
                super.MAXatkRtg = 45;
                super.critChance = 7;
                super.MINblock = 4;
                super.MAXblock = 4;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 4;
                super.Display = 1;
                super.weight = 6;
                super.price = 2600;
                super.itemLore = "";

                break;

            case "13-Broad Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Broad Sword";
                super.itemImgDir = "/assets/item/weapon/sword/13.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 13;
                super.rStr = 50;
                super.rTal = 36;
                super.MINintegrity = 52;
                super.MAXintegrity = 63;
                super.MINatkMin = 5;
                super.MAXatkMin = 8;
                super.MINatkMax = 10;
                super.MAXatkMax = 12;
                super.atkSpd = 6;
                super.MINatkRtg = 45;
                super.MAXatkRtg = 53;
                super.critChance = 5;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 9;
                super.price = 3500;
                super.itemLore = "";

                break;

            case "17-Blade":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Blade";
                super.itemImgDir = "/assets/item/weapon/sword/17.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 17;
                super.rStr = 62;
                super.rAgi = 40;
                super.MINintegrity = 48;
                super.MAXintegrity = 70;
                super.MINatkMin = 6;
                super.MAXatkMin = 9;
                super.MINatkMax = 11;
                super.MAXatkMax = 14;
                super.atkSpd = 7;
                super.MINatkRtg = 45;
                super.MAXatkRtg = 52;
                super.critChance = 5;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 4;
                super.sDivAtkPow = 4;
                super.Display = 1;
                super.weight = 8;
                super.price = 5400;
                super.itemLore = "";

                break;

            case "24-Templar Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Templar Sword";
                super.itemImgDir = "/assets/item/weapon/sword/24.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 24;
                super.rStr = 40;
                super.rSpi = 30;
                super.rTal = 40;
                super.MINintegrity = 45;
                super.MAXintegrity = 65;
                super.MINatkMin = 7;
                super.MAXatkMin = 9;
                super.MINatkMax = 13;
                super.MAXatkMax = 15;
                super.atkSpd = 7;
                super.MINatkRtg = 42;
                super.MAXatkRtg = 46;
                super.critChance = 6;
                super.MINmp = 10;
                super.MAXmp = 16;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.Display = 1;
                super.weight = 8;
                super.price = 9300;
                super.itemLore = "";

                break;

            case "30-Shield Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Shield Sword";
                super.itemImgDir = "/assets/item/weapon/sword/30.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 30;
                super.rStr = 66;
                super.rTal = 52;
                super.rAgi = 40;
                super.MINintegrity = 50;
                super.MAXintegrity = 75;
                super.MINatkMin = 8;
                super.MAXatkMin = 12;
                super.MINatkMax = 16;
                super.MAXatkMax = 18;
                super.atkSpd = 7;
                super.MINatkRtg = 45;
                super.MAXatkRtg = 56;
                super.critChance = 7;
                super.MINdefense = 6;
                super.MAXdefense = 10;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sMINdefense = 10;
                super.sMAXdefense = 16;
                super.sCritChance = 4;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 9;
                super.price = 13000;
                super.itemLore = "";

                break;

            case "37-Plated Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Plated Sword";
                super.itemImgDir = "/assets/item/weapon/sword/37.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 37;
                super.rStr = 76;
                super.rTal = 82;
                super.MINintegrity = 60;
                super.MAXintegrity = 80;
                super.MINatkMin = 13;
                super.MAXatkMin = 16;
                super.MINatkMax = 21;
                super.MAXatkMax = 26;
                super.atkSpd = 7;
                super.MINatkRtg = 50;
                super.MAXatkRtg = 62;
                super.critChance = 12;
                super.MINblock = 7;
                super.MAXblock = 7;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 13;
                super.price = 16000;
                super.itemLore = "";

                break;

            case "40-Platinum Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Platinum Sword";
                super.itemImgDir = "/assets/item/weapon/sword/37.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 40;
                super.MINintegrity = 100;
                super.MAXintegrity = 100;
                super.MINatkMin = 17;
                super.MAXatkMin = 17;
                super.MINatkMax = 22;
                super.MAXatkMax = 22;
                super.atkSpd = 8;
                super.MINatkRtg = 100;
                super.MAXatkRtg = 100;
                super.critChance = 12;
                super.MINblock = 7;
                super.MAXblock = 7;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.Display = 1;
                super.weight = 13;
                super.price = 30000;
                super.itemLore = "";

                break;

            case "43-Claymore":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Claymore";
                super.itemImgDir = "/assets/item/weapon/sword/43.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 43;
                super.rStr = 80;
                super.rTal = 75;
                super.rAgi = 50;
                super.MINintegrity = 66;
                super.MAXintegrity = 84;
                super.MINatkMin = 11;
                super.MAXatkMin = 14;
                super.MINatkMax = 21;
                super.MAXatkMax = 23;
                super.atkSpd = 7;
                super.MINatkRtg = 60;
                super.MAXatkRtg = 70;
                super.critChance = 7;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 12;
                super.price = 21000;
                super.itemLore = "";

                break;

            case "48-Slayer":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Slayer";
                super.itemImgDir = "/assets/item/weapon/sword/48.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 48;
                super.rStr = 90;
                super.rTal = 80;
                super.rAgi = 56;
                super.MINintegrity = 73;
                super.MAXintegrity = 92;
                super.MINatkMin = 13;
                super.MAXatkMin = 16;
                super.MINatkMax = 24;
                super.MAXatkMax = 27;
                super.atkSpd = 6;
                super.MINatkRtg = 70;
                super.MAXatkRtg = 84;
                super.critChance = 8;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 2;
                super.sCritChance = 3;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 13;
                super.price = 27000;
                super.itemLore = "";

                break;

            case "53-Gigantic Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Gigantic Sword";
                super.itemImgDir = "/assets/item/weapon/sword/53.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 53;
                super.rStr = 115;
                super.rTal = 80;
                super.MINintegrity = 85;
                super.MAXintegrity = 100;
                super.MINatkMin = 19;
                super.MAXatkMin = 22;
                super.MINatkMax = 32;
                super.MAXatkMax = 35;
                super.atkSpd = 7;
                super.MINatkRtg = 80;
                super.MAXatkRtg = 100;
                super.critChance = 14;
                super.MINblock = 8;
                super.MAXblock = 8;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 20;
                super.price = 34000;
                super.itemLore = "";

                break;

            case "57-Highlander":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Highlander";
                super.itemImgDir = "/assets/item/weapon/sword/57.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 57;
                super.rStr = 110;
                super.rTal = 86;
                super.MINintegrity = 80;
                super.MAXintegrity = 105;
                super.MINatkMin = 16;
                super.MAXatkMin = 20;
                super.MINatkMax = 28;
                super.MAXatkMax = 31;
                super.atkSpd = 7;
                super.MINatkRtg = 85;
                super.MAXatkRtg = 98;
                super.critChance = 9;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 4;
                super.sDivAtkPow = 7;
                super.Display = 1;
                super.weight = 26;
                super.price = 41000;
                super.itemLore = "";

                break;

            case "61-Bastard Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Bastard Sword";
                super.itemImgDir = "/assets/item/weapon/sword/61.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 61;
                super.rStr = 124;
                super.rTal = 90;
                super.MINintegrity = 75;
                super.MAXintegrity = 115;
                super.MINatkMin = 23;
                super.MAXatkMin = 26;
                super.MINatkMax = 36;
                super.MAXatkMax = 40;
                super.atkSpd = 7;
                super.MINatkRtg = 100;
                super.MAXatkRtg = 114;
                super.critChance = 16;
                super.MINblock = 9;
                super.MAXblock = 9;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 7;
                super.sDivAtkPow = 5;
                super.Display = 1;
                super.weight = 28;
                super.price = 48000;
                super.itemLore = "";

                break;

            case "65-Fatal Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Fatal Sword";
                super.itemImgDir = "/assets/item/weapon/sword/65.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 65;
                super.rStr = 130;
                super.rTal = 90;
                super.MINintegrity = 80;
                super.MAXintegrity = 120;
                super.MINatkMin = 25;
                super.MAXatkMin = 29;
                super.MINatkMax = 39;
                super.MAXatkMax = 44;
                super.atkSpd = 7;
                super.MINatkRtg = 110;
                super.MAXatkRtg = 130;
                super.critChance = 17;
                super.MINblock = 8;
                super.MAXblock = 8;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 36;
                super.price = 57000;
                super.itemLore = "";

                break;

            case "70-Ancient Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Ancient Sword";
                super.itemImgDir = "/assets/item/weapon/sword/70.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 70;
                super.rStr = 100;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 65;
                super.MAXintegrity = 120;
                super.MINatkMin = 22;
                super.MAXatkMin = 26;
                super.MINatkMax = 35;
                super.MAXatkMax = 38;
                super.atkSpd = 7;
                super.MINatkRtg = 100;
                super.MAXatkRtg = 120;
                super.critChance = 11;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 6;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 30;
                super.price = 66000;
                super.itemLore = "";

                break;

            case "75-Twin Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Twin Sword";
                super.itemImgDir = "/assets/item/weapon/sword/75.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 75;
                super.rStr = 126;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 85;
                super.MAXintegrity = 130;
                super.MINatkMin = 32;
                super.MAXatkMin = 35;
                super.MINatkMax = 48;
                super.MAXatkMax = 51;
                super.atkSpd = 7;
                super.MINatkRtg = 118;
                super.MAXatkRtg = 142;
                super.critChance = 18;
                super.MINblock = 9;
                super.MAXblock = 9;
                super.MINmp = 20;
                super.MAXmp = 30;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 4;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 33;
                super.price = 150000;
                super.itemLore = "";

                break;

            case "80-Salamander Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Salamander Sword";
                super.itemImgDir = "/assets/item/weapon/sword/80.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 80;
                super.rStr = 134;
                super.rTal = 90;
                super.MINintegrity = 95;
                super.MAXintegrity = 136;
                super.MINatkMin = 38;
                super.MAXatkMin = 42;
                super.MINatkMax = 53;
                super.MAXatkMax = 56;
                super.atkSpd = 7;
                super.MINatkRtg = 126;
                super.MAXatkRtg = 150;
                super.critChance = 18;
                super.MINblock = 10;
                super.MAXblock = 10;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 4;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 38;
                super.price = 260000;
                super.itemLore = "";

                break;

            case "84-Avanger Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Avanger Sword";
                super.itemImgDir = "/assets/item/weapon/sword/84.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 84;
                super.rStr = 130;
                super.rTal = 90;
                super.MINintegrity = 90;
                super.MAXintegrity = 125;
                super.MINatkMin = 34;
                super.MAXatkMin = 36;
                super.MINatkMax = 47;
                super.MAXatkMax = 50;
                super.atkSpd = 8;
                super.MINatkRtg = 130;
                super.MAXatkRtg = 156;
                super.critChance = 11;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 3;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 36;
                super.price = 430000;
                super.itemLore = "";

                break;

            case "88-Titan Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Titan Sword";
                super.itemImgDir = "/assets/item/weapon/sword/88.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 88;
                super.rStr = 144;
                super.rTal = 90;
                super.MINintegrity = 110;
                super.MAXintegrity = 140;
                super.MINatkMin = 47;
                super.MAXatkMin = 50;
                super.MINatkMax = 63;
                super.MAXatkMax = 66;
                super.atkSpd = 8;
                super.MINatkRtg = 136;
                super.MAXatkRtg = 164;
                super.critChance = 18;
                super.MINblock = 10;
                super.MAXblock = 10;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 48;
                super.price = 690000;
                super.itemLore = "";

                break;

            case "92-Wyvern Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Wyvern Sword";
                super.itemImgDir = "/assets/item/weapon/sword/92.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 92;
                super.rStr = 152;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 110;
                super.MAXintegrity = 136;
                super.MINatkMin = 36;
                super.MAXatkMin = 39;
                super.MINatkMax = 51;
                super.MAXatkMax = 55;
                super.atkSpd = 7;
                super.MINatkRtg = 144;
                super.MAXatkRtg = 170;
                super.critChance = 12;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sAtkSpd = 1;
                super.sCritChance = 3;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 52;
                super.price = 1200000;
                super.itemLore = "";

                break;

            case "96-Dragon Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Dragon Sword";
                super.itemImgDir = "/assets/item/weapon/sword/96.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 96;
                super.rStr = 168;
                super.rTal = 90;
                super.MINintegrity = 126;
                super.MAXintegrity = 155;
                super.MINatkMin = 52;
                super.MAXatkMin = 54;
                super.MINatkMax = 71;
                super.MAXatkMax = 74;
                super.atkSpd = 8;
                super.MINatkRtg = 160;
                super.MAXatkRtg = 164;
                super.critChance = 20;
                super.MINblock = 12;
                super.MAXblock = 12;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 58;
                super.price = 1300000;
                super.itemLore = "";

                break;

            case "98-Silver Blade":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Silver Blade";
                super.itemImgDir = "/assets/item/weapon/sword/98.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 98;
                super.rStr = 174;
                super.rSpi = 50;
                super.rTal = 90;
                super.MINintegrity = 135;
                super.MAXintegrity = 162;
                super.MINatkMin = 38;
                super.MAXatkMin = 42;
                super.MINatkMax = 55;
                super.MAXatkMax = 58;
                super.atkSpd = 8;
                super.MINatkRtg = 164;
                super.MAXatkRtg = 169;
                super.critChance = 13;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 60;
                super.price = 1400000;
                super.itemLore = "";

                break;

            case "100-Predator":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Predator";
                super.itemImgDir = "/assets/item/weapon/sword/100.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 100;
                super.rStr = 180;
                super.rSpi = 60;
                super.rTal = 90;
                super.MINintegrity = 142;
                super.MAXintegrity = 170;
                super.MINatkMin = 42;
                super.MAXatkMin = 46;
                super.MINatkMax = 60;
                super.MAXatkMax = 64;
                super.atkSpd = 8;
                super.MINatkRtg = 172;
                super.MAXatkRtg = 178;
                super.critChance = 13;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 62;
                super.price = 1500000;
                super.itemLore = "";

                break;

            case "104-Justice Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Justice Sword";
                super.itemImgDir = "/assets/item/weapon/sword/104.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 104;
                super.rStr = 182;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 150;
                super.MAXintegrity = 176;
                super.MINatkMin = 58;
                super.MAXatkMin = 61;
                super.MINatkMax = 81;
                super.MAXatkMax = 85;
                super.atkSpd = 8;
                super.MINatkRtg = 168;
                super.MAXatkRtg = 192;
                super.critChance = 21;
                super.MINblock = 14;
                super.MAXblock = 14;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 64;
                super.price = 1600000;
                super.itemLore = "";

                break;

            case "106-Inferno Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Inferno Sword";
                super.itemImgDir = "/assets/item/weapon/sword/106.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 106;
                super.rStr = 196;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 156;
                super.MAXintegrity = 162;
                super.MINatkMin = 50;
                super.MAXatkMin = 52;
                super.MINatkMax = 69;
                super.MAXatkMax = 72;
                super.atkSpd = 8;
                super.MINatkRtg = 185;
                super.MAXatkRtg = 211;
                super.critChance = 16;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 5;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 66;
                super.price = 1700000;
                super.itemLore = "";

                break;

            case "110-Extreme Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Extreme Sword";
                super.itemImgDir = "/assets/item/weapon/sword/110.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 110;
                super.rStr = 210;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 162;
                super.MAXintegrity = 170;
                super.MINatkMin = 75;
                super.MAXatkMin = 78;
                super.MINatkMax = 104;
                super.MAXatkMax = 109;
                super.atkSpd = 8;
                super.MINatkRtg = 203;
                super.MAXatkRtg = 232;
                super.critChance = 22;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 6;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 68;
                super.price = 1800000;
                super.itemLore = "";

                break;

            case "114-Imperial Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Imperial Sword";
                super.itemImgDir = "/assets/item/weapon/sword/114.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 114;
                super.rStr = 224;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 168;
                super.MAXintegrity = 178;
                super.MINatkMin = 66;
                super.MAXatkMin = 69;
                super.MINatkMax = 85;
                super.MAXatkMax = 87;
                super.atkSpd = 8;
                super.MINatkRtg = 220;
                super.MAXatkRtg = 239;
                super.critChance = 16;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 6;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 70;
                super.price = 1900000;
                super.itemLore = "";

                break;

            case "116-Emperor Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Emperor Sword";
                super.itemImgDir = "/assets/item/weapon/sword/116.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 116;
                super.rStr = 230;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 170;
                super.MAXintegrity = 180;
                super.MINatkMin = 86;
                super.MAXatkMin = 89;
                super.MINatkMax = 107;
                super.MAXatkMax = 112;
                super.atkSpd = 8;
                super.MINatkRtg = 228;
                super.MAXatkRtg = 259;
                super.critChance = 22;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 6;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 72;
                super.price = 1950000;
                super.itemLore = "";

                break;

            case "120-Mirage Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Mirage Sword";
                super.itemImgDir = "/assets/item/weapon/sword/120.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 120;
                super.rStr = 240;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 177;
                super.MAXintegrity = 188;
                super.MINatkMin = 93;
                super.MAXatkMin = 96;
                super.MINatkMax = 109;
                super.MAXatkMax = 114;
                super.atkSpd = 8;
                super.MINatkRtg = 240;
                super.MAXatkRtg = 270;
                super.critChance = 22;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 75;
                super.price = 2000000;
                super.itemLore = "";

                break;

            case "122-Relic Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Relic Sword";
                super.itemImgDir = "/assets/item/weapon/sword/122.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 122;
                super.rStr = 258;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 186;
                super.MAXintegrity = 197;
                super.MINatkMin = 72;
                super.MAXatkMin = 75;
                super.MINatkMax = 92;
                super.MAXatkMax = 94;
                super.atkSpd = 8;
                super.MINatkRtg = 255;
                super.MAXatkRtg = 285;
                super.critChance = 16;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 6;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 72;
                super.price = 2100000;
                super.itemLore = "";

                break;

            case "126-Tirbing Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Tirbing Sword";
                super.itemImgDir = "/assets/item/weapon/sword/126.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 126;
                super.rStr = 270;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 200;
                super.MAXintegrity = 210;
                super.MINatkMin = 102;
                super.MAXatkMin = 105;
                super.MINatkMax = 114;
                super.MAXatkMax = 120;
                super.atkSpd = 8;
                super.MINatkRtg = 260;
                super.MAXatkRtg = 290;
                super.critChance = 22;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 80;
                super.price = 2200000;
                super.itemLore = "";

                break;

            case "130-Mythology Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Mythology Sword";
                super.itemImgDir = "/assets/item/weapon/sword/130.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 130;
                super.rStr = 290;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 210;
                super.MAXintegrity = 220;
                super.MINatkMin = 111;
                super.MAXatkMin = 114;
                super.MINatkMax = 119;
                super.MAXatkMax = 125;
                super.atkSpd = 8;
                super.MINatkRtg = 280;
                super.MAXatkRtg = 310;
                super.critChance = 22;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 90;
                super.price = 2300000;
                super.itemLore = "";

                break;

            case "134-Deadly Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Deadly Sword";
                super.itemImgDir = "/assets/item/weapon/sword/134.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 134;
                super.rStr = 310;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 220;
                super.MAXintegrity = 230;
                super.MINatkMin = 120;
                super.MAXatkMin = 123;
                super.MINatkMax = 128;
                super.MAXatkMax = 134;
                super.atkSpd = 8;
                super.MINatkRtg = 300;
                super.MAXatkRtg = 330;
                super.critChance = 23;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 90;
                super.price = 2400000;
                super.itemLore = "";

                break;

            case "138-Hellbringer Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "Hellbringer Sword";
                super.itemImgDir = "/assets/item/weapon/sword/138.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 138;
                super.rStr = 330;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 230;
                super.MAXintegrity = 240;
                super.MINatkMin = 129;
                super.MAXatkMin = 132;
                super.MINatkMax = 137;
                super.MAXatkMax = 143;
                super.atkSpd = 8;
                super.MINatkRtg = 328;
                super.MAXatkRtg = 360;
                super.critChance = 23;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.Display = 1;
                super.weight = 98;
                super.price = 2790000;
                super.itemLore = "";

                break;

            case "160-WS232 Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "WS232 Sword";
                super.itemImgDir = "/assets/item/weapon/sword/160.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 160;
                super.rStr = 310;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 220;
                super.MAXintegrity = 230;
                super.MINatkMin = 120;
                super.MAXatkMin = 123;
                super.MINatkMax = 128;
                super.MAXatkMax = 134;
                super.atkSpd = 8;
                super.MINatkRtg = 300;
                super.MAXatkRtg = 330;
                super.critChance = 23;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.weight = 90;
                super.price = 2400000;
                super.itemLore = "";

                break;

            case "160-WS233 Sword":
                super.itemClass = "Melee";
                super.itemType = "Sword";
                super.itemName = "WS233 Sword";
                super.itemImgDir = "/assets/item/weapon/sword/160.png";
                super.itemIconDir = ICON_2H_SWORD;
                super.oneOrTwoHanded = TWO_HANDED;
                super.rLvl = 160;
                super.rStr = 310;
                super.rSpi = 40;
                super.rTal = 90;
                super.MINintegrity = 220;
                super.MAXintegrity = 230;
                super.MINatkMin = 120;
                super.MAXatkMin = 123;
                super.MINatkMax = 128;
                super.MAXatkMax = 134;
                super.atkSpd = 8;
                super.MINatkRtg = 300;
                super.MAXatkRtg = 330;
                super.critChance = 23;
                super.MINblock = 15;
                super.MAXblock = 15;
                super.classSpec[0] = MS;
                super.classSpec[1] = FS;
                super.classSpec[2] = PS;
                super.classSpec[3] = AS;
                super.classSpec[4] = ASS;
                super.classSpec[5] = KS;
                super.classSpec[6] = ATS;
                super.classSpec[7] = PRS;
                super.classSpec[8] = MGS;
                super.classSpec[9] = SS;
                super.classSpec[10] = NS;
                super.sCritChance = 7;
                super.sMINDivAtkRtg = 1;
                super.sMAXDivAtkRtg = 3;
                super.sDivAtkPow = 6;
                super.weight = 90;
                super.price = 2400000;
                super.itemLore = "";

                break;

        }
    }
}
