/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Luiz
 */
public class BattleFrame extends javax.swing.JFrame {

    /**
     * Creates new form BattleFrame
     */
    public BattleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPlayerCornerScreen = new javax.swing.JPanel();
        lblCornerClanIconP = new javax.swing.JLabel();
        lblCornerClanNameP = new javax.swing.JLabel();
        lblCornerClanNameShadowP = new javax.swing.JLabel();
        lblCornerNameP = new javax.swing.JLabel();
        lblCornerNameShadowP = new javax.swing.JLabel();
        lblCornerHPBarP = new javax.swing.JLabel();
        lblCornerHPFrameP = new javax.swing.JLabel();
        lblCornerCharPortraitP = new javax.swing.JLabel();
        lblCornerFrameP = new javax.swing.JLabel();
        panEnemyCornerScreen = new javax.swing.JPanel();
        lblCornerClanIconE = new javax.swing.JLabel();
        lblCornerClanNameE = new javax.swing.JLabel();
        lblCornerClanNameShadowE = new javax.swing.JLabel();
        lblCornerNameE = new javax.swing.JLabel();
        lblCornerNameShadowE = new javax.swing.JLabel();
        lblCornerHPBarE = new javax.swing.JLabel();
        lblCornerHPFrameE = new javax.swing.JLabel();
        lblCornerCharPortraitE = new javax.swing.JLabel();
        lblCornerFrameE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        panPlayerCornerScreen.setOpaque(false);
        panPlayerCornerScreen.setLayout(null);

        lblCornerClanIconP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerClanIconP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/CLANNAME_clanIcon.png"))); // NOI18N
        panPlayerCornerScreen.add(lblCornerClanIconP);
        lblCornerClanIconP.setBounds(4, 4, 32, 32);

        lblCornerClanNameP.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCornerClanNameP.setForeground(new java.awt.Color(150, 255, 200));
        lblCornerClanNameP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCornerClanNameP.setText("KnightHood");
        panPlayerCornerScreen.add(lblCornerClanNameP);
        lblCornerClanNameP.setBounds(40, 4, 90, 20);

        lblCornerClanNameShadowP.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCornerClanNameShadowP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCornerClanNameShadowP.setText("KnightHood");
        panPlayerCornerScreen.add(lblCornerClanNameShadowP);
        lblCornerClanNameShadowP.setBounds(41, 5, 90, 20);

        lblCornerNameP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCornerNameP.setForeground(new java.awt.Color(255, 255, 255));
        lblCornerNameP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerNameP.setText("DarkLink64");
        panPlayerCornerScreen.add(lblCornerNameP);
        lblCornerNameP.setBounds(2, 108, 124, 20);

        lblCornerNameShadowP.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCornerNameShadowP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerNameShadowP.setText("DarkLink64");
        panPlayerCornerScreen.add(lblCornerNameShadowP);
        lblCornerNameShadowP.setBounds(3, 109, 124, 20);

        lblCornerHPBarP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerHPBarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornerhpbar.png"))); // NOI18N
        panPlayerCornerScreen.add(lblCornerHPBarP);
        lblCornerHPBarP.setBounds(7, 133, 110, 7);

        lblCornerHPFrameP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerHPFrameP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornerhpframe.png"))); // NOI18N
        panPlayerCornerScreen.add(lblCornerHPFrameP);
        lblCornerHPFrameP.setBounds(4, 130, 117, 13);

        lblCornerCharPortraitP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerCharPortraitP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/Knight01_frame.png"))); // NOI18N
        panPlayerCornerScreen.add(lblCornerCharPortraitP);
        lblCornerCharPortraitP.setBounds(0, 0, 126, 126);

        lblCornerFrameP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerFrameP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornercharframe.png"))); // NOI18N
        panPlayerCornerScreen.add(lblCornerFrameP);
        lblCornerFrameP.setBounds(0, 0, 126, 126);

        getContentPane().add(panPlayerCornerScreen);
        panPlayerCornerScreen.setBounds(9, 9, 126, 143);

        panEnemyCornerScreen.setOpaque(false);
        panEnemyCornerScreen.setLayout(null);

        lblCornerClanIconE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerClanIconE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/CLANNAME_clanIcon.png"))); // NOI18N
        panEnemyCornerScreen.add(lblCornerClanIconE);
        lblCornerClanIconE.setBounds(4, 4, 32, 32);

        lblCornerClanNameE.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCornerClanNameE.setForeground(new java.awt.Color(150, 255, 200));
        lblCornerClanNameE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCornerClanNameE.setText("BowlingBash");
        panEnemyCornerScreen.add(lblCornerClanNameE);
        lblCornerClanNameE.setBounds(40, 4, 90, 20);

        lblCornerClanNameShadowE.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblCornerClanNameShadowE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCornerClanNameShadowE.setText("BowlingBash");
        panEnemyCornerScreen.add(lblCornerClanNameShadowE);
        lblCornerClanNameShadowE.setBounds(41, 5, 90, 20);

        lblCornerNameE.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCornerNameE.setForeground(new java.awt.Color(255, 255, 255));
        lblCornerNameE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerNameE.setText("DarkLink64");
        panEnemyCornerScreen.add(lblCornerNameE);
        lblCornerNameE.setBounds(2, 108, 124, 20);

        lblCornerNameShadowE.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblCornerNameShadowE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerNameShadowE.setText("DarkLink64");
        panEnemyCornerScreen.add(lblCornerNameShadowE);
        lblCornerNameShadowE.setBounds(3, 109, 124, 20);

        lblCornerHPBarE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerHPBarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornerhpbar.png"))); // NOI18N
        panEnemyCornerScreen.add(lblCornerHPBarE);
        lblCornerHPBarE.setBounds(7, 133, 110, 7);

        lblCornerHPFrameE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerHPFrameE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornerhpframe.png"))); // NOI18N
        panEnemyCornerScreen.add(lblCornerHPFrameE);
        lblCornerHPFrameE.setBounds(4, 130, 117, 13);

        lblCornerCharPortraitE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerCharPortraitE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/Knight02_frame.png"))); // NOI18N
        panEnemyCornerScreen.add(lblCornerCharPortraitE);
        lblCornerCharPortraitE.setBounds(0, 0, 126, 126);

        lblCornerFrameE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCornerFrameE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/battle/cornerscreen/cornercharframe.png"))); // NOI18N
        panEnemyCornerScreen.add(lblCornerFrameE);
        lblCornerFrameE.setBounds(0, 0, 126, 126);

        getContentPane().add(panEnemyCornerScreen);
        panEnemyCornerScreen.setBounds(1145, 9, 126, 143);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCornerCharPortraitE;
    private javax.swing.JLabel lblCornerCharPortraitP;
    private javax.swing.JLabel lblCornerClanIconE;
    private javax.swing.JLabel lblCornerClanIconP;
    private javax.swing.JLabel lblCornerClanNameE;
    private javax.swing.JLabel lblCornerClanNameP;
    private javax.swing.JLabel lblCornerClanNameShadowE;
    private javax.swing.JLabel lblCornerClanNameShadowP;
    private javax.swing.JLabel lblCornerFrameE;
    private javax.swing.JLabel lblCornerFrameP;
    private javax.swing.JLabel lblCornerHPBarE;
    private javax.swing.JLabel lblCornerHPBarP;
    private javax.swing.JLabel lblCornerHPFrameE;
    private javax.swing.JLabel lblCornerHPFrameP;
    private javax.swing.JLabel lblCornerNameE;
    private javax.swing.JLabel lblCornerNameP;
    private javax.swing.JLabel lblCornerNameShadowE;
    private javax.swing.JLabel lblCornerNameShadowP;
    private javax.swing.JPanel panEnemyCornerScreen;
    private javax.swing.JPanel panPlayerCornerScreen;
    // End of variables declaration//GEN-END:variables
}
