/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import animation.FadeInOut;
import animation.ShowCharSelectBtn;
import animation.CharSelect;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Administrator
 */
public class CharSelectFrame extends javax.swing.JFrame {

    int indexArrayBtn = 0;
    ArrayList<JButton> listTempskron = new ArrayList<>();
    ArrayList<JButton> listMorion = new ArrayList<>();
    CharSelect animPlayer = new CharSelect();
    CharSelect animEnemy = new CharSelect();
    boolean playerSelecting = true;
    

    /**
     * Creates new form CharSelectFrame
     */
    public CharSelectFrame() {

        initComponents();
        popularListaTempskronBtn();
        popularListaMorionBtn();

        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            public void run() {

                if (indexArrayBtn <= 4) {
                    ShowCharSelectBtn scsb = new ShowCharSelectBtn();
                    scsb.showUp(listTempskron.get(indexArrayBtn), 390, 0, 25, true);
                } else if (indexArrayBtn <= 9) {
                    ShowCharSelectBtn scsb = new ShowCharSelectBtn();
                    scsb.showUp(listMorion.get(indexArrayBtn - 5), 490, 0, 15, true);
                } else {
                    timer.cancel();
                }
                indexArrayBtn++;
            }
        };

        Sound.playSound("CharacterSelect.wav");
        getContentPane().setBackground(Color.BLACK);
        FadeInOut fadeBackGround = new FadeInOut();
        fadeBackGround.animarFade(lblBackground, 5, 60, "/assets/images/charselectbackground.png", true, false, 0);
        timer.scheduleAtFixedRate(task, 100, 100);
        
        CustomCursor();
        
        FadeInOut fadeCharPlayer = new FadeInOut();
        FadeInOut fadeCharEnemy = new FadeInOut();
        
        fadeCharPlayer.animarFade(lblPlayer, 10, 60, "/assets/images/character/ks_player.png", true, false, 0);
        fadeCharEnemy.animarFade(lblEnemy, 10, 60, "/assets/images/character/ks_enemy.png", true, false, 0);
        
        
        

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblEnemy = new javax.swing.JLabel();
        lblMorions = new javax.swing.JLabel();
        lblMorions1 = new javax.swing.JLabel();
        btnArcher = new javax.swing.JButton();
        btnKnight = new javax.swing.JButton();
        btnMagician = new javax.swing.JButton();
        btnPriestess = new javax.swing.JButton();
        btnAtalanta = new javax.swing.JButton();
        btnShaman = new javax.swing.JButton();
        btnFighter = new javax.swing.JButton();
        btnAssassin = new javax.swing.JButton();
        btnMechanician = new javax.swing.JButton();
        btnPikeman = new javax.swing.JButton();
        lblVersus = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 630));
        setMinimumSize(new java.awt.Dimension(800, 630));
        setPreferredSize(new java.awt.Dimension(800, 630));
        getContentPane().setLayout(null);

        jButton1.setText("Player/Enemy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(595, 10, 130, 23);
        getContentPane().add(lblEnemy);
        lblEnemy.setBounds(410, 0, 370, 480);

        lblMorions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/logoTempskrons.png"))); // NOI18N
        getContentPane().add(lblMorions);
        lblMorions.setBounds(20, 350, 126, 124);

        lblMorions1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/logoMorions.png"))); // NOI18N
        getContentPane().add(lblMorions1);
        lblMorions1.setBounds(20, 470, 126, 124);

        btnArcher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/archer.png"))); // NOI18N
        btnArcher.setBorderPainted(false);
        btnArcher.setContentAreaFilled(false);
        btnArcher.setFocusPainted(false);
        btnArcher.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/archer.png"))); // NOI18N
        btnArcher.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/archer_hover.png"))); // NOI18N
        btnArcher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArcherMouseEntered(evt);
            }
        });
        btnArcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcherActionPerformed(evt);
            }
        });
        getContentPane().add(btnArcher);
        btnArcher.setBounds(190, 600, 88, 88);

        btnKnight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/knight.png"))); // NOI18N
        btnKnight.setBorderPainted(false);
        btnKnight.setContentAreaFilled(false);
        btnKnight.setFocusPainted(false);
        btnKnight.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/knight.png"))); // NOI18N
        btnKnight.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/knight_hover.png"))); // NOI18N
        btnKnight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKnightMouseEntered(evt);
            }
        });
        btnKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnightActionPerformed(evt);
            }
        });
        getContentPane().add(btnKnight);
        btnKnight.setBounds(290, 600, 88, 88);

        btnMagician.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/magician.png"))); // NOI18N
        btnMagician.setBorderPainted(false);
        btnMagician.setContentAreaFilled(false);
        btnMagician.setFocusPainted(false);
        btnMagician.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/magician.png"))); // NOI18N
        btnMagician.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/magician_hover.png"))); // NOI18N
        btnMagician.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMagicianMouseEntered(evt);
            }
        });
        btnMagician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMagicianActionPerformed(evt);
            }
        });
        getContentPane().add(btnMagician);
        btnMagician.setBounds(490, 600, 88, 88);

        btnPriestess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/priestess.png"))); // NOI18N
        btnPriestess.setBorderPainted(false);
        btnPriestess.setContentAreaFilled(false);
        btnPriestess.setFocusPainted(false);
        btnPriestess.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/priestess.png"))); // NOI18N
        btnPriestess.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/priestess_hover.png"))); // NOI18N
        btnPriestess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPriestessMouseEntered(evt);
            }
        });
        btnPriestess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriestessActionPerformed(evt);
            }
        });
        getContentPane().add(btnPriestess);
        btnPriestess.setBounds(590, 600, 88, 88);

        btnAtalanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/atalanta.png"))); // NOI18N
        btnAtalanta.setBorderPainted(false);
        btnAtalanta.setContentAreaFilled(false);
        btnAtalanta.setFocusPainted(false);
        btnAtalanta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/atalanta.png"))); // NOI18N
        btnAtalanta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/atalanta_hover.png"))); // NOI18N
        btnAtalanta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtalantaMouseEntered(evt);
            }
        });
        btnAtalanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtalantaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtalanta);
        btnAtalanta.setBounds(190, 600, 88, 88);

        btnShaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/shaman.png"))); // NOI18N
        btnShaman.setBorderPainted(false);
        btnShaman.setContentAreaFilled(false);
        btnShaman.setFocusPainted(false);
        btnShaman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/shaman.png"))); // NOI18N
        btnShaman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/shaman_hover.png"))); // NOI18N
        btnShaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShamanMouseEntered(evt);
            }
        });
        btnShaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShamanActionPerformed(evt);
            }
        });
        getContentPane().add(btnShaman);
        btnShaman.setBounds(390, 600, 88, 88);

        btnFighter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/fighter.png"))); // NOI18N
        btnFighter.setBorderPainted(false);
        btnFighter.setContentAreaFilled(false);
        btnFighter.setFocusPainted(false);
        btnFighter.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/fighter.png"))); // NOI18N
        btnFighter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/fighter_hover.png"))); // NOI18N
        btnFighter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFighterMouseEntered(evt);
            }
        });
        btnFighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFighterActionPerformed(evt);
            }
        });
        getContentPane().add(btnFighter);
        btnFighter.setBounds(290, 600, 88, 88);

        btnAssassin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/assassin.png"))); // NOI18N
        btnAssassin.setBorderPainted(false);
        btnAssassin.setContentAreaFilled(false);
        btnAssassin.setFocusPainted(false);
        btnAssassin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/assassin.png"))); // NOI18N
        btnAssassin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/assassin_hover.png"))); // NOI18N
        btnAssassin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssassinMouseEntered(evt);
            }
        });
        btnAssassin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssassinActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssassin);
        btnAssassin.setBounds(390, 600, 88, 88);

        btnMechanician.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/mechanician.png"))); // NOI18N
        btnMechanician.setBorderPainted(false);
        btnMechanician.setContentAreaFilled(false);
        btnMechanician.setFocusPainted(false);
        btnMechanician.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/mechanician.png"))); // NOI18N
        btnMechanician.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/mechanician_hover.png"))); // NOI18N
        btnMechanician.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMechanicianMouseEntered(evt);
            }
        });
        btnMechanician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMechanicianActionPerformed(evt);
            }
        });
        getContentPane().add(btnMechanician);
        btnMechanician.setBounds(490, 600, 88, 88);

        btnPikeman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/pikeman.png"))); // NOI18N
        btnPikeman.setBorderPainted(false);
        btnPikeman.setContentAreaFilled(false);
        btnPikeman.setFocusPainted(false);
        btnPikeman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/pikeman.png"))); // NOI18N
        btnPikeman.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/classicon/pikeman_hover.png"))); // NOI18N
        btnPikeman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPikemanMouseEntered(evt);
            }
        });
        btnPikeman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPikemanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPikeman);
        btnPikeman.setBounds(590, 600, 88, 88);

        lblVersus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/vs.png"))); // NOI18N
        lblVersus.setText("vs");
        getContentPane().add(lblVersus);
        lblVersus.setBounds(330, 300, 140, 90);
        getContentPane().add(lblPlayer);
        lblPlayer.setBounds(140, 0, 370, 480);
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKnightActionPerformed

    private void btnMagicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMagicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMagicianActionPerformed

    private void btnPriestessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriestessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPriestessActionPerformed

    private void btnAtalantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtalantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtalantaActionPerformed

    private void btnShamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShamanActionPerformed

    private void btnArcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArcherActionPerformed

    private void btnFighterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFighterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFighterActionPerformed

    private void btnAssassinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssassinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssassinActionPerformed

    private void btnMechanicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMechanicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMechanicianActionPerformed

    private void btnPikemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPikemanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPikemanActionPerformed

    private void btnKnightMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKnightMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ks_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ks_enemy.png", 810, 410, 30, playerSelecting);
        }
        
    }//GEN-LAST:event_btnKnightMouseEntered

    private void btnArcherMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArcherMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/as_player.png", -380, 80, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/as_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnArcherMouseEntered

    private void btnMagicianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMagicianMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/mg_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/mg_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnMagicianMouseEntered

    private void btnPriestessMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPriestessMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/prs_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/prs_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnPriestessMouseEntered

    private void btnAtalantaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtalantaMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ata_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ata_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnAtalantaMouseEntered

    private void btnShamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShamanMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ss_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ss_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnShamanMouseEntered

    private void btnFighterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFighterMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/fs_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/fs_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnFighterMouseEntered

    private void btnAssassinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssassinMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ass_player.png", -380, 140, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ass_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnAssassinMouseEntered

    private void btnMechanicianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMechanicianMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ms_player.png", -380, 80, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ms_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnMechanicianMouseEntered

    private void btnPikemanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPikemanMouseEntered
        if (playerSelecting) {
            animPlayer.showUp(lblPlayer, "/assets/images/character/ps_player.png", -380, 1, 30, playerSelecting);
        } else {
            animPlayer.showUp(lblEnemy, "/assets/images/character/ps_enemy.png", 810, 410, 30, playerSelecting);
        }
    }//GEN-LAST:event_btnPikemanMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (playerSelecting) {
            playerSelecting = false;
        } else {
            playerSelecting = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharSelectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharSelectFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArcher;
    private javax.swing.JButton btnAssassin;
    private javax.swing.JButton btnAtalanta;
    private javax.swing.JButton btnFighter;
    private javax.swing.JButton btnKnight;
    private javax.swing.JButton btnMagician;
    private javax.swing.JButton btnMechanician;
    private javax.swing.JButton btnPikeman;
    private javax.swing.JButton btnPriestess;
    private javax.swing.JButton btnShaman;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblMorions;
    private javax.swing.JLabel lblMorions1;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblVersus;
    // End of variables declaration//GEN-END:variables

    private void popularListaTempskronBtn() {
        listTempskron.add(btnArcher);
        listTempskron.add(btnMechanician);
        listTempskron.add(btnAssassin);
        listTempskron.add(btnFighter);
        listTempskron.add(btnPikeman);
        Collections.shuffle(listTempskron);

    }

    private void popularListaMorionBtn() {
        listMorion.add(btnAtalanta);
        listMorion.add(btnKnight);
        listMorion.add(btnShaman);
        listMorion.add(btnMagician);
        listMorion.add(btnPriestess);
        Collections.shuffle(listMorion);

    }
    
    public void CustomCursor()
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("default.png");
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        
        setCursor(cursor);
    }
}
