/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Administrator
 */
public class JdiConfirm extends javax.swing.JDialog {

    int returnFlag;
    
    public JdiConfirm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        CustomCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagem = new javax.swing.JLabel();
        btnBuild = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSwap = new javax.swing.JButton();
        lblPlayerClass = new javax.swing.JLabel();
        lblEnemyClass = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(429, 166));
        setMinimumSize(new java.awt.Dimension(429, 166));
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblMensagem.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setText("Please, confirm your character selection.");
        getContentPane().add(lblMensagem);
        lblMensagem.setBounds(30, 20, 370, 21);

        btnBuild.setText("Build it!");
        btnBuild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuild);
        btnBuild.setBounds(320, 110, 67, 23);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(30, 110, 77, 23);

        btnSwap.setText("Swap Characters");
        btnSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwapActionPerformed(evt);
            }
        });
        getContentPane().add(btnSwap);
        btnSwap.setBounds(170, 110, 140, 23);

        lblPlayerClass.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayerClass.setText("Player: Knight");
        getContentPane().add(lblPlayerClass);
        lblPlayerClass.setBounds(30, 50, 340, 14);

        lblEnemyClass.setForeground(new java.awt.Color(255, 255, 255));
        lblEnemyClass.setText("Enemy: Knight");
        getContentPane().add(lblEnemyClass);
        lblEnemyClass.setBounds(30, 70, 350, 14);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/msgBox.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 428, 167);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        returnFlag = 0;
        clickBotao();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwapActionPerformed
        returnFlag = 1;
        clickBotao();
    }//GEN-LAST:event_btnSwapActionPerformed

    private void btnBuildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildActionPerformed
        returnFlag = 2;
        clickBotao();
    }//GEN-LAST:event_btnBuildActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdiConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdiConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdiConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdiConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdiConfirm dialog = new JdiConfirm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuild;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSwap;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEnemyClass;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblPlayerClass;
    // End of variables declaration//GEN-END:variables

    public void setPlayerChar(String playerClass) {
        lblPlayerClass.setText("Player: " + playerClass);
    }

    public void setEnemyChar(String enemyClass) {
        lblEnemyClass.setText("Enemy: " + enemyClass);
    }
    
    private void clickBotao(){
        this.setVisible(false);
        this.dispose();
    }
    
    public void CustomCursor() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("default.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");

        setCursor(cursor);
    }
}
