/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author LuizV1
 */
public class JdiGearSelector extends javax.swing.JDialog {

    /**
     * Creates new form JdiGearSelector
     */
    public JdiGearSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panGearSelect = new javax.swing.JPanel();
        itemSelect = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JList<String>();
        jPanel9 = new javax.swing.JPanel();
        lblGearImage = new javax.swing.JLabel();
        lblGearDesc = new javax.swing.JLabel();
        cmbAgingLevel = new javax.swing.JComboBox<String>();
        cmbMix = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnEquip = new javax.swing.JButton();
        cmbSpec = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        btnFecharGearSelect = new javax.swing.JButton();
        rbtAcessory = new javax.swing.JRadioButton();
        rbtWeapon = new javax.swing.JRadioButton();
        rbtDefense = new javax.swing.JRadioButton();
        rbtType10 = new javax.swing.JRadioButton();
        rbtType1 = new javax.swing.JRadioButton();
        rbtType2 = new javax.swing.JRadioButton();
        rbtType3 = new javax.swing.JRadioButton();
        rbtType4 = new javax.swing.JRadioButton();
        rbtType5 = new javax.swing.JRadioButton();
        rbtType6 = new javax.swing.JRadioButton();
        rbtType7 = new javax.swing.JRadioButton();
        rbtType8 = new javax.swing.JRadioButton();
        rbtType9 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panGearSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panGearSelect.setLayout(null);

        itemSelect.setLayout(null);

        listItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listItem);

        itemSelect.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 180, 340);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(null);

        lblGearImage.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.add(lblGearImage);
        lblGearImage.setBounds(20, 90, 70, 100);

        lblGearDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblGearDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel9.add(lblGearDesc);
        lblGearDesc.setBounds(110, 10, 160, 320);

        itemSelect.add(jPanel9);
        jPanel9.setBounds(200, 10, 290, 340);

        cmbAgingLevel.setMaximumRowCount(23);
        cmbAgingLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+0", "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9", "+10", "+11", "+12", "+13", "+14", "+15", "+16", "+17", "+18", "+19", "+20", "+21", "+22" }));
        cmbAgingLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgingLevelActionPerformed(evt);
            }
        });
        itemSelect.add(cmbAgingLevel);
        cmbAgingLevel.setBounds(500, 30, 220, 20);

        cmbMix.setMaximumRowCount(15);
        cmbMix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        itemSelect.add(cmbMix);
        cmbMix.setBounds(500, 80, 220, 20);

        jLabel12.setText("Aging:");
        itemSelect.add(jLabel12);
        jLabel12.setBounds(500, 10, 220, 14);

        jLabel13.setText("Mix:");
        itemSelect.add(jLabel13);
        jLabel13.setBounds(500, 60, 220, 14);

        btnEquip.setText("Equip");
        btnEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipActionPerformed(evt);
            }
        });
        itemSelect.add(btnEquip);
        btnEquip.setBounds(660, 330, 59, 23);

        cmbSpec.setMaximumRowCount(11);
        cmbSpec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        itemSelect.add(cmbSpec);
        cmbSpec.setBounds(500, 130, 120, 20);

        jLabel11.setText("Select Class Spec:");
        itemSelect.add(jLabel11);
        jLabel11.setBounds(500, 110, 110, 14);

        btnFecharGearSelect.setText("Close");
        btnFecharGearSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharGearSelectActionPerformed(evt);
            }
        });
        itemSelect.add(btnFecharGearSelect);
        btnFecharGearSelect.setBounds(500, 330, 59, 23);

        panGearSelect.add(itemSelect);
        itemSelect.setBounds(10, 50, 730, 360);

        rbtAcessory.setText("Acessory");
        rbtAcessory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAcessoryActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtAcessory);
        rbtAcessory.setBounds(150, 5, 70, 20);

        rbtWeapon.setSelected(true);
        rbtWeapon.setText("Weapon");
        rbtWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtWeaponActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtWeapon);
        rbtWeapon.setBounds(10, 5, 70, 20);

        rbtDefense.setText("Defense");
        rbtDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDefenseActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtDefense);
        rbtDefense.setBounds(80, 5, 70, 20);

        rbtType10.setText("Phantom");
        rbtType10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType10ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType10);
        rbtType10.setBounds(640, 30, 70, 15);

        rbtType1.setText("Sword");
        rbtType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType1ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType1);
        rbtType1.setBounds(10, 30, 70, 15);

        rbtType2.setText("Axe");
        rbtType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType2ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType2);
        rbtType2.setBounds(80, 30, 70, 15);

        rbtType3.setText("Hammer");
        rbtType3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType3ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType3);
        rbtType3.setBounds(150, 30, 70, 15);

        rbtType4.setText("Claw");
        rbtType4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType4ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType4);
        rbtType4.setBounds(220, 30, 70, 15);

        rbtType5.setText("Scythe");
        rbtType5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType5ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType5);
        rbtType5.setBounds(290, 30, 70, 15);

        rbtType6.setText("Dagger");
        rbtType6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType6ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType6);
        rbtType6.setBounds(360, 30, 70, 15);

        rbtType7.setText("Bow");
        rbtType7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType7ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType7);
        rbtType7.setBounds(430, 30, 70, 15);

        rbtType8.setText("Javelin");
        rbtType8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType8ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType8);
        rbtType8.setBounds(500, 30, 70, 15);

        rbtType9.setText("Wand");
        rbtType9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType9ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType9);
        rbtType9.setBounds(570, 30, 70, 15);
        panGearSelect.add(jSeparator1);
        jSeparator1.setBounds(10, 25, 725, 5);

        getContentPane().add(panGearSelect);
        panGearSelect.setBounds(0, 0, 750, 425);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listItemMouseClicked
        switch (listItem.getSelectedValue()) {
            case "138-HellBringer Sword":
            selectedGear = new Sword138();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "122-Relic Sword":
            selectedGear = new Sword122();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Quantum Armor":
            selectedGear = new Armor140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Imperial Shield":
            selectedGear = new Shield140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "138-Draxos Boots":
            selectedGear = new Boots138();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Mercurial Gauntlets":
            selectedGear = new Gauntlet140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "136-Greedy Gauntlets":
            selectedGear = new Gauntlet136();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Mercurial Bracelets":
            selectedGear = new Bracelet140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Sheltom":
            selectedGear = new SheltomSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Ring":
            selectedGear = new RingSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Amulet":
            selectedGear = new NecklaceSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            default:
            break;
        }
    }//GEN-LAST:event_listItemMouseClicked

    private void cmbAgingLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgingLevelActionPerformed
        selectedGear.addAging(cmbAgingLevel.getSelectedIndex());
        lblGearDesc.setText(selectedGear.getItemDesc());
    }//GEN-LAST:event_cmbAgingLevelActionPerformed

    private void btnEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipActionPerformed
        animGear.open(panGearSelect, false);
        panStatsFields.setVisible(true);
        equiparItem();
    }//GEN-LAST:event_btnEquipActionPerformed

    private void btnFecharGearSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharGearSelectActionPerformed
        animGear.open(panGearSelect, false);
        panStatsFields.setVisible(true);
    }//GEN-LAST:event_btnFecharGearSelectActionPerformed

    private void rbtAcessoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAcessoryActionPerformed
        setGearSelectAcessory();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtAcessoryActionPerformed

    private void rbtWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtWeaponActionPerformed
        setGearSelectWeapon();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtWeaponActionPerformed

    private void rbtDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDefenseActionPerformed
        setGearSelectDefense();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtDefenseActionPerformed

    private void rbtType10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType10ActionPerformed
        switch (rbtType9.getText()) {
            case "Phantom":
            popularListaPhantom();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType10ActionPerformed

    private void rbtType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType1ActionPerformed
        switch (rbtType1.getText()) {
            case "Sword":
            popularListaSword();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Armor":
            popularListaArmor();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Necklace":
            popularListaNecklace();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType1ActionPerformed

    private void rbtType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType2ActionPerformed
        switch (rbtType2.getText()) {
            case "Axe":
            popularListaAxe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Robe":
            popularListaRobe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Ring":
            popularListaRing();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType2ActionPerformed

    private void rbtType3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType3ActionPerformed
        switch (rbtType3.getText()) {
            case "Hammer":
            popularListaHammer();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Shield":
            popularListaShield();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Sheltom":
            popularListaSheltom();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType3ActionPerformed

    private void rbtType4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType4ActionPerformed
        switch (rbtType4.getText()) {
            case "Claw":
            popularListaClaw();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Orb":
            popularListaOrb();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType4ActionPerformed

    private void rbtType5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType5ActionPerformed
        switch (rbtType5.getText()) {
            case "Scythe":
            popularListaScythe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Bracelet":
            popularListaBracelet();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType5ActionPerformed

    private void rbtType6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType6ActionPerformed
        switch (rbtType6.getText()) {
            case "Dagger":
            popularListaDagger();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Gauntlet":
            popularListaGauntlet();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType6ActionPerformed

    private void rbtType7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType7ActionPerformed
        switch (rbtType7.getText()) {
            case "Bow":
            popularListaBow();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Boots":
            popularListaBoots();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType7ActionPerformed

    private void rbtType8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType8ActionPerformed
        switch (rbtType8.getText()) {
            case "Javeling":
            popularListaJavelin();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType8ActionPerformed

    private void rbtType9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType9ActionPerformed
        switch (rbtType9.getText()) {
            case "Wand":
            popularListaWand();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdiGearSelector dialog = new JdiGearSelector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquip;
    private javax.swing.JButton btnFecharGearSelect;
    private javax.swing.JComboBox<String> cmbAgingLevel;
    private javax.swing.JComboBox<String> cmbMix;
    private javax.swing.JComboBox<String> cmbSpec;
    private javax.swing.JPanel itemSelect;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGearDesc;
    private javax.swing.JLabel lblGearImage;
    private javax.swing.JList<String> listItem;
    private javax.swing.JPanel panGearSelect;
    private javax.swing.JRadioButton rbtAcessory;
    private javax.swing.JRadioButton rbtDefense;
    private javax.swing.JRadioButton rbtType1;
    private javax.swing.JRadioButton rbtType10;
    private javax.swing.JRadioButton rbtType2;
    private javax.swing.JRadioButton rbtType3;
    private javax.swing.JRadioButton rbtType4;
    private javax.swing.JRadioButton rbtType5;
    private javax.swing.JRadioButton rbtType6;
    private javax.swing.JRadioButton rbtType7;
    private javax.swing.JRadioButton rbtType8;
    private javax.swing.JRadioButton rbtType9;
    private javax.swing.JRadioButton rbtWeapon;
    // End of variables declaration//GEN-END:variables
}
