/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author LuizV1
 */
public class JdiGearSelector extends javax.swing.JDialog {
    
    String callType;
    boolean playerOrEnemy;
    private final boolean PLAYER = true;
    private final boolean ENEMY = false;
    private final boolean ONEHAND = true;
    private final boolean TWOHAND = false;
    
    public JdiGearSelector(java.awt.Frame parent, boolean modal, String callType, boolean playerOrEnemy) {
        super(parent, modal);
        this.callType = callType;
        this.playerOrEnemy = playerOrEnemy;
        initComponents();
    }

    private JdiGearSelector(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panGearSelect = new javax.swing.JPanel();
        itemSelect = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JList<String>();
        panItem = new javax.swing.JPanel();
        lblGearImage = new javax.swing.JLabel();
        lblGearDesc = new javax.swing.JLabel();
        panCompareItem = new javax.swing.JPanel();
        lblGearImageC = new javax.swing.JLabel();
        lblGearDescC = new javax.swing.JLabel();
        cmbAgingLevel = new javax.swing.JComboBox<String>();
        cmbMix = new javax.swing.JComboBox<String>();
        lblAging = new javax.swing.JLabel();
        lblMix = new javax.swing.JLabel();
        btnEquip = new javax.swing.JButton();
        cmbSpec = new javax.swing.JComboBox<String>();
        lblClassSpec = new javax.swing.JLabel();
        btnFecharGearSelect = new javax.swing.JButton();
        lblAgingC = new javax.swing.JLabel();
        lblMixC = new javax.swing.JLabel();
        lblClassSpecC = new javax.swing.JLabel();
        cmbAgingLevelC = new javax.swing.JComboBox<String>();
        cmbMixC = new javax.swing.JComboBox<String>();
        cmbSpecC = new javax.swing.JComboBox<String>();
        rbtAcessory = new javax.swing.JRadioButton();
        rbtWeapon = new javax.swing.JRadioButton();
        rbtDefense = new javax.swing.JRadioButton();
        rbtType10 = new javax.swing.JRadioButton();
        rbtType1 = new javax.swing.JRadioButton();
        rbtType2 = new javax.swing.JRadioButton();
        rbtType3 = new javax.swing.JRadioButton();
        rbtType4 = new javax.swing.JRadioButton();
        rbtType5 = new javax.swing.JRadioButton();
        rbtType6 = new javax.swing.JRadioButton();
        rbtType7 = new javax.swing.JRadioButton();
        rbtType8 = new javax.swing.JRadioButton();
        rbtType9 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        panGearSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panGearSelect.setLayout(null);

        itemSelect.setLayout(null);

        listItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listItem);

        itemSelect.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 130, 280);

        panItem.setBackground(new java.awt.Color(0, 0, 0));
        panItem.setLayout(null);

        lblGearImage.setBackground(new java.awt.Color(255, 255, 255));
        panItem.add(lblGearImage);
        lblGearImage.setBounds(5, 90, 70, 100);

        lblGearDesc.setForeground(new java.awt.Color(255, 255, 255));
        lblGearDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panItem.add(lblGearDesc);
        lblGearDesc.setBounds(80, 0, 160, 280);

        itemSelect.add(panItem);
        panItem.setBounds(135, 0, 240, 280);

        panCompareItem.setBackground(new java.awt.Color(0, 0, 0));
        panCompareItem.setLayout(null);

        lblGearImageC.setBackground(new java.awt.Color(255, 255, 255));
        panCompareItem.add(lblGearImageC);
        lblGearImageC.setBounds(5, 90, 70, 100);

        lblGearDescC.setForeground(new java.awt.Color(255, 255, 255));
        lblGearDescC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panCompareItem.add(lblGearDescC);
        lblGearDescC.setBounds(80, 0, 160, 280);

        itemSelect.add(panCompareItem);
        panCompareItem.setBounds(390, 0, 240, 280);

        cmbAgingLevel.setMaximumRowCount(23);
        cmbAgingLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+0", "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9", "+10", "+11", "+12", "+13", "+14", "+15", "+16", "+17", "+18", "+19", "+20", "+21", "+22" }));
        cmbAgingLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgingLevelActionPerformed(evt);
            }
        });
        itemSelect.add(cmbAgingLevel);
        cmbAgingLevel.setBounds(135, 310, 50, 20);

        cmbMix.setMaximumRowCount(15);
        cmbMix.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        itemSelect.add(cmbMix);
        cmbMix.setBounds(195, 310, 80, 20);

        lblAging.setText("Aging:");
        itemSelect.add(lblAging);
        lblAging.setBounds(135, 290, 50, 14);

        lblMix.setText("Mix:");
        itemSelect.add(lblMix);
        lblMix.setBounds(195, 290, 90, 14);

        btnEquip.setText("Equip");
        btnEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipActionPerformed(evt);
            }
        });
        itemSelect.add(btnEquip);
        btnEquip.setBounds(10, 290, 110, 40);

        cmbSpec.setMaximumRowCount(11);
        cmbSpec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        itemSelect.add(cmbSpec);
        cmbSpec.setBounds(285, 310, 90, 20);

        lblClassSpec.setText("Class Spec:");
        itemSelect.add(lblClassSpec);
        lblClassSpec.setBounds(285, 290, 100, 14);

        btnFecharGearSelect.setText("Close");
        btnFecharGearSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharGearSelectActionPerformed(evt);
            }
        });
        itemSelect.add(btnFecharGearSelect);
        btnFecharGearSelect.setBounds(640, 290, 70, 40);

        lblAgingC.setText("Aging:");
        itemSelect.add(lblAgingC);
        lblAgingC.setBounds(390, 290, 50, 14);

        lblMixC.setText("Mix:");
        itemSelect.add(lblMixC);
        lblMixC.setBounds(450, 290, 90, 14);

        lblClassSpecC.setText("Class Spec:");
        itemSelect.add(lblClassSpecC);
        lblClassSpecC.setBounds(540, 290, 100, 14);

        cmbAgingLevelC.setMaximumRowCount(23);
        cmbAgingLevelC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+0", "+1", "+2", "+3", "+4", "+5", "+6", "+7", "+8", "+9", "+10", "+11", "+12", "+13", "+14", "+15", "+16", "+17", "+18", "+19", "+20", "+21", "+22" }));
        cmbAgingLevelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAgingLevelCActionPerformed(evt);
            }
        });
        itemSelect.add(cmbAgingLevelC);
        cmbAgingLevelC.setBounds(390, 310, 50, 20);

        cmbMixC.setMaximumRowCount(15);
        cmbMixC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        itemSelect.add(cmbMixC);
        cmbMixC.setBounds(450, 310, 80, 20);

        cmbSpecC.setMaximumRowCount(11);
        cmbSpecC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        itemSelect.add(cmbSpecC);
        cmbSpecC.setBounds(540, 310, 90, 20);

        panGearSelect.add(itemSelect);
        itemSelect.setBounds(5, 50, 730, 340);

        rbtAcessory.setText("Acessory");
        rbtAcessory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAcessoryActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtAcessory);
        rbtAcessory.setBounds(150, 5, 70, 20);

        rbtWeapon.setSelected(true);
        rbtWeapon.setText("Weapon");
        rbtWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtWeaponActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtWeapon);
        rbtWeapon.setBounds(10, 5, 70, 20);

        rbtDefense.setText("Defense");
        rbtDefense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtDefenseActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtDefense);
        rbtDefense.setBounds(80, 5, 70, 20);

        rbtType10.setText("Phantom");
        rbtType10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType10ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType10);
        rbtType10.setBounds(640, 30, 70, 15);

        rbtType1.setText("Sword");
        rbtType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType1ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType1);
        rbtType1.setBounds(10, 30, 70, 15);

        rbtType2.setText("Axe");
        rbtType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType2ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType2);
        rbtType2.setBounds(80, 30, 70, 15);

        rbtType3.setText("Hammer");
        rbtType3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType3ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType3);
        rbtType3.setBounds(150, 30, 70, 15);

        rbtType4.setText("Claw");
        rbtType4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType4ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType4);
        rbtType4.setBounds(220, 30, 70, 15);

        rbtType5.setText("Scythe");
        rbtType5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType5ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType5);
        rbtType5.setBounds(290, 30, 70, 15);

        rbtType6.setText("Dagger");
        rbtType6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType6ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType6);
        rbtType6.setBounds(360, 30, 70, 15);

        rbtType7.setText("Bow");
        rbtType7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType7ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType7);
        rbtType7.setBounds(430, 30, 70, 15);

        rbtType8.setText("Javelin");
        rbtType8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType8ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType8);
        rbtType8.setBounds(500, 30, 70, 15);

        rbtType9.setText("Wand");
        rbtType9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtType9ActionPerformed(evt);
            }
        });
        panGearSelect.add(rbtType9);
        rbtType9.setBounds(570, 30, 70, 15);
        panGearSelect.add(jSeparator1);
        jSeparator1.setBounds(10, 25, 725, 5);

        getContentPane().add(panGearSelect);
        panGearSelect.setBounds(0, 0, 740, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void definirBotoes(){
        String charname;
        if (playerOrEnemy = PLAYER){
            charname = main.player;
        } else {
            charname = main.enemy;
        }
        switch (callType){
            case "1h,melee":
                rbtWeapon.setEnabled(true);
                rbtDefense.setEnabled(false);
                rbtAcessory.setEnabled(false);
                rbtWeapon.setSelected(true);
                rbtType1.setEnabled(true);
                rbtType2.setEnabled(true);
                rbtType3.setEnabled(true);
                rbtType4.setEnabled(true);
                rbtType5.setEnabled(true);
                rbtType6.setEnabled(true);
                rbtType7.setEnabled(true);
                rbtType8.setEnabled(true);
                rbtType9.setEnabled(false);
                rbtType10.setEnabled(false);                
            switch (charname) {
                case "Knight":
                    rbtType1.setSelected(true);
                    popularListaSword
                case "Fighter":
            }
        }
    }
    
    private void popularListaSword(boolean hand){
        DefaultListModel model = new DefaultListModel();
        if (hand = ONEHAND){            
            for ();
        } else {
            model.addElement();
        }
        listItem.setModel(model);
    }
    
    private void listItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listItemMouseClicked
        switch (listItem.getSelectedValue()) {
            case "138-HellBringer Sword":
            selectedGear = new Sword138();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "122-Relic Sword":
            selectedGear = new Sword122();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Quantum Armor":
            selectedGear = new Armor140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Imperial Shield":
            selectedGear = new Shield140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "138-Draxos Boots":
            selectedGear = new Boots138();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Mercurial Gauntlets":
            selectedGear = new Gauntlet140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "136-Greedy Gauntlets":
            selectedGear = new Gauntlet136();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "140-Mercurial Bracelets":
            selectedGear = new Bracelet140();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Sheltom":
            selectedGear = new SheltomSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Ring":
            selectedGear = new RingSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            case "120-Throne Amulet":
            selectedGear = new NecklaceSB3();
            lblGearDesc.setText(selectedGear.getItemDesc());
            lblGearImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(selectedGear.getItemImgDir())));
            break;
            default:
            break;
        }
    }//GEN-LAST:event_listItemMouseClicked

    private void cmbAgingLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgingLevelActionPerformed
        selectedGear.addAging(cmbAgingLevel.getSelectedIndex());
        lblGearDesc.setText(selectedGear.getItemDesc());
    }//GEN-LAST:event_cmbAgingLevelActionPerformed

    private void btnEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipActionPerformed
        animGear.open(panGearSelect, false);
        panStatsFields.setVisible(true);
        equiparItem();
    }//GEN-LAST:event_btnEquipActionPerformed

    private void btnFecharGearSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharGearSelectActionPerformed
        animGear.open(panGearSelect, false);
        panStatsFields.setVisible(true);
    }//GEN-LAST:event_btnFecharGearSelectActionPerformed

    private void rbtAcessoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAcessoryActionPerformed
        setGearSelectAcessory();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtAcessoryActionPerformed

    private void rbtWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtWeaponActionPerformed
        setGearSelectWeapon();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtWeaponActionPerformed

    private void rbtDefenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtDefenseActionPerformed
        setGearSelectDefense();
        btnGrupoItemType.clearSelection();
    }//GEN-LAST:event_rbtDefenseActionPerformed

    private void rbtType10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType10ActionPerformed
        switch (rbtType9.getText()) {
            case "Phantom":
            popularListaPhantom();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType10ActionPerformed

    private void rbtType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType1ActionPerformed
        switch (rbtType1.getText()) {
            case "Sword":
            popularListaSword();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Armor":
            popularListaArmor();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Necklace":
            popularListaNecklace();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType1ActionPerformed

    private void rbtType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType2ActionPerformed
        switch (rbtType2.getText()) {
            case "Axe":
            popularListaAxe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Robe":
            popularListaRobe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Ring":
            popularListaRing();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType2ActionPerformed

    private void rbtType3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType3ActionPerformed
        switch (rbtType3.getText()) {
            case "Hammer":
            popularListaHammer();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Shield":
            popularListaShield();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Sheltom":
            popularListaSheltom();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType3ActionPerformed

    private void rbtType4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType4ActionPerformed
        switch (rbtType4.getText()) {
            case "Claw":
            popularListaClaw();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Orb":
            popularListaOrb();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType4ActionPerformed

    private void rbtType5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType5ActionPerformed
        switch (rbtType5.getText()) {
            case "Scythe":
            popularListaScythe();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Bracelet":
            popularListaBracelet();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType5ActionPerformed

    private void rbtType6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType6ActionPerformed
        switch (rbtType6.getText()) {
            case "Dagger":
            popularListaDagger();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Gauntlet":
            popularListaGauntlet();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType6ActionPerformed

    private void rbtType7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType7ActionPerformed
        switch (rbtType7.getText()) {
            case "Bow":
            popularListaBow();
            cmbAgingLevel.setEnabled(true);
            break;
            case "Boots":
            popularListaBoots();
            cmbAgingLevel.setEnabled(false);
            break;
        }
    }//GEN-LAST:event_rbtType7ActionPerformed

    private void rbtType8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType8ActionPerformed
        switch (rbtType8.getText()) {
            case "Javeling":
            popularListaJavelin();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType8ActionPerformed

    private void rbtType9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtType9ActionPerformed
        switch (rbtType9.getText()) {
            case "Wand":
            popularListaWand();
            cmbAgingLevel.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_rbtType9ActionPerformed

    private void cmbAgingLevelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAgingLevelCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAgingLevelCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdiGearSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdiGearSelector dialog = new JdiGearSelector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquip;
    private javax.swing.JButton btnFecharGearSelect;
    private javax.swing.JComboBox<String> cmbAgingLevel;
    private javax.swing.JComboBox<String> cmbAgingLevelC;
    private javax.swing.JComboBox<String> cmbMix;
    private javax.swing.JComboBox<String> cmbMixC;
    private javax.swing.JComboBox<String> cmbSpec;
    private javax.swing.JComboBox<String> cmbSpecC;
    private javax.swing.JPanel itemSelect;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAging;
    private javax.swing.JLabel lblAgingC;
    private javax.swing.JLabel lblClassSpec;
    private javax.swing.JLabel lblClassSpecC;
    private javax.swing.JLabel lblGearDesc;
    private javax.swing.JLabel lblGearDescC;
    private javax.swing.JLabel lblGearImage;
    private javax.swing.JLabel lblGearImageC;
    private javax.swing.JLabel lblMix;
    private javax.swing.JLabel lblMixC;
    private javax.swing.JList<String> listItem;
    private javax.swing.JPanel panCompareItem;
    private javax.swing.JPanel panGearSelect;
    private javax.swing.JPanel panItem;
    private javax.swing.JRadioButton rbtAcessory;
    private javax.swing.JRadioButton rbtDefense;
    private javax.swing.JRadioButton rbtType1;
    private javax.swing.JRadioButton rbtType10;
    private javax.swing.JRadioButton rbtType2;
    private javax.swing.JRadioButton rbtType3;
    private javax.swing.JRadioButton rbtType4;
    private javax.swing.JRadioButton rbtType5;
    private javax.swing.JRadioButton rbtType6;
    private javax.swing.JRadioButton rbtType7;
    private javax.swing.JRadioButton rbtType8;
    private javax.swing.JRadioButton rbtType9;
    private javax.swing.JRadioButton rbtWeapon;
    // End of variables declaration//GEN-END:variables
}
